services:
  postgres:
    image: postgres:17-alpine
    environment:
      POSTGRES_USER: tributum
      POSTGRES_PASSWORD: tributum_pass
      POSTGRES_DB: tributum_db
    volumes:
      - ./docker/postgres/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U tributum -d tributum_db"]
      interval: 2s
      timeout: 5s
      retries: 15
