"""Initial empty migration.

Revision ID: 1e32d8f148c9
Revises:
Create Date: 2025-06-23 11:44:04.932042
"""

from collections.abc import Sequence

# revision identifiers, used by Alembic.
revision: str = "1e32d8f148c9"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # ### end Alembic commands ###
